### ISSUE TITLE
API documentation needed

### ISSUE THREAD

**Issue by kapilrc** [Festify/cordova-external-screen#1]
Hi, thanks for this wonderful plugin. Could we get some API documentation on how to use this plugin? 

Thanks in advance.
Kapil

**Comment by NeoLegends** [comment]
Right now there's no documentation, but you can see in https://github.com/Festify/cordova-external-screen/blob/master/www/cordova-external-screen.js and https://github.com/Festify/cordova-external-screen/blob/master/src/ios/ScreenNotificationDelegate.m that the API is really really simple. Just two methods on the class and two events `connect` and `disconnect` thrown when a screen connects or disconnects. :)

**Comment by kapilk2** [comment]
Hi @NeoLegends how can I receive the event data on Airplay TV?

here is my code 

```
cordova.plugins.externalScreen.createScreenListener().then(res => {
        Externalscreen = res;

        //register events
        Externalscreen.on("disconnect", r => console.log("disconnected", r), e => console.error("unable to disconnect", e));
        Externalscreen.on("connect", r => console.log("connected", r), e => console.error("unable to connect", e));
      
      Externalscreen.loadUrl("presentation/airplay.html");
      Externalscreen.emit("name",{data});

});
```

`Externalscreen && Externalscreen.on("emit", evt => console.log(evt))`

how do I call `emit` in airplay.html?

thanks in advance :)

**Comment by NeoLegends** [comment]
You can't communicate with the web view using the event emitter as they are two isolated entities. You'll have to use an out-of-band mechanism (like a server) to pass data between the website on the second screen and your main application.
